buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url "http://dl.google.com/dl/android/maven2"
            allowInsecureProtocol = true
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.1"   // понижаем до 1.7.1
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "http://dl.google.com/dl/android/maven2"
            allowInsecureProtocol = true
        }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}